/** @format */

export const jwtConstants = {
  secret: 'jwtConstants',
};

export const DB = {
  SEQUELIZE: 'SEQUELIZE',
  DATA_SOURCE: 'DATA_SOURCE',
  USERS_REPOSITORY: 'USERS_REPOSITORY',
  OTP_REPOSITORY: 'OTP_REPOSITORY',
  TRANSACTION_REPOSITORY: 'TRANSACTION_REPOSITORY',
  APP_SERVICES_REPOSITORY: 'APP_SERVICES_REPOSITORY',
  USER_APP_SERVICES_REPOSITORY: 'USER_APP_SERVICES_REPOSITORY',
  WALLETS_REPOSITORY: 'WALLETS_REPOSITORY',
  DEVICES_REPOSITORY: 'DEVICES_REPOSITORY',
};

export const MONGODB = {
  DATABASE_CONNECTION: 'DATABASE_CONNECTION',
  EXCHANGE_RATE_MODEL: 'EXCHANGE_RATE_MODEL',
};
